services:
  db:
    image: postgres:16.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
    restart: always
  backend:
    build: ./backend
    container_name: Todo-backend
    ports:
      - "8080:8080"
    environment:
      DB_CONT_NAME: db
      DB_PORT: 5432
      DB_DATABASE: db
    depends_on:
      - db
    restart: always
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: Todo-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  db: